---
- name: 'Configure WIFI'
  copy: src=./wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600

- name: 'Add Chromium repository key'
  apt_key: url=http://bintray.com/user/downloadSubjectPublicKey?username=bintray state=present

- name: 'Add Chromium repository'
  apt_repository: repo="deb http://dl.bintray.com/kusti8/chromium-rpi jessie main" state=present

- name: 'Update APT package cache'
  action: apt update_cache=yes

- name: 'Upgrade APT to the lastest packages'
  action: apt upgrade=safe

- name: 'Install Chromium'
  apt: name=chromium-browser state=present

- name: 'Install unclutter command'
  apt: name=unclutter state=present

- name: 'Install x11vnc'
  apt: name=x11vnc state=present

- name: 'Configure boot parameters'
  template: src=templates/config.txt dest=/boot/config.txt owner=root group=root mode=0644

- name: 'Ensure autostart directory exists'
  file:
    path: "/home/pi/.config/autostart"
    state: directory
    recurse: yes
    owner: pi
    group: pi

- name: 'Configure VNC'
  template: src=templates/x11vnc.desktop dest=/home/pi/.config/autostart/x11vnc.desktop owner=pi group=pi mode=0755

- name: 'Disable screen sleep'
  template: src=templates/lightdm.conf dest=/etc/lightdm/lightdm.conf owner=root group=root mode=0644

- name: 'Setup LXDE autostart file'
  template: src=templates/autostart dest=/home/pi/.config/lxsession/LXDE-pi/autostart owner=pi group=pi mode=0644

- name: 'Reboot'
  command: /sbin/reboot
